USE SYS;

USE EMPLOYEES;

SELECT * FROM DEPARTMENTS;
SELECT * FROM DEPT_EMP;
SELECT * FROM DEPT_MANAGER;
SELECT * FROM EMPLOYEES;
SELECT * FROM SALARIES;
SELECT * FROM TITLES;

SELECT * FROM DEPARTMENTS;

SELECT DEPT_NO FROM DEPARTMENTS
WHERE  DEPT_NAME = "FINANCE";

SELECT * FROM EMPLOYEES
WHERE GENDER="M";

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE "%S";

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE "_S%";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "A%";

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE "E%";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "I%";

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE "O%";

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE "U%";

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE"%A";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "%E";

SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE "%I";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "%O";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "%U";

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE "S%";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "%S%";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "%_A_%";

SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE "_PS___%";

SELECT DEPT_NO FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE "ELVIS";

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE "KELLIE" AND GENDER ="F";

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME LIKE "KELLIE" AND GENDER ="F" OR  FIRST_NAME LIKE "ARUNA" AND GENDER = "F";

SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME ="KELLIE" OR  FIRST_NAME ="ARUNA";

